ARG NODE_VERSION=14.17.6
FROM node:${NODE_VERSION}
WORKDIR /var/www/

COPY package*.json ./

RUN npm install

COPY . .

RUN npm run build

ENV ADDRESS 5000
EXPOSE $ADDRESS

CMD ["npm", "run", "serve"]